services:
  rps:
    container_name: rps
    build: .
    restart: unless-stopped
    expose:
      - "8000"
    environment:
      - NODE_ENV=production
    networks:
      - proxy_network

networks:
  proxy_network:
    external: true
